---
name: Perl CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl: ['5.32', '5.34', '5.36', '5.38']

    name: Perl ${{ matrix.perl }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}

      - name: Install dependencies
        run: |
          cpanm -n --installdeps --with-develop .

      - name: Run tests
        run: |
          perl Makefile.PL
          make
          make test
